import Topbar from "./Topbar";
import Aside from "./Aside";
import Footer from "./Footer";
import Head from "next/head";
export default function Layout ({ children }) {
  return (
    <>
      <Head>
        <title>Fresh Cart</title>
        <link rel="icon" href="/images/logo.jpeg" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Topbar />
      <Aside />
      {children}
      <Footer />
    </>
  );
};
